### ISSUE TITLE
SRS

### ISSUE THREAD

**Issue by shoamco** [shoamco/Smart-School-reshit#1]
[srs_wc.docx](https://github.com/shoamco/Smart-School-reshit/files/611806/srs_wc.docx)

![9e6a4e80-b0cb-11e6-935b-eb7b56993516](https://cloud.githubusercontent.com/assets/23197636/20604316/75a15666-b26e-11e6-9c28-b2090dad7830.PNG)
![9e6e1948-b0cb-11e6-84c2-d45d751e6086](https://cloud.githubusercontent.com/assets/23197636/20604317/75a885b2-b26e-11e6-8a2f-4775e7b1a50c.PNG)

**Comment by robi-y** [comment]
please assign @hadarp (if needed, remind her by mail or chat to accept your
invitation - it's a new secure thing)
