### ISSUE TITLE
staff member can see his pages

### ISSUE THREAD

**Issue by shoamco** [shoamco/Smart-School-reshit#22]
*	בתור מנהל - אני מעוניין בממשק שיאפשר לראות את כל כיתות בית הספר, עבור כל כיתה תוצג רשימת כל התלמידים, עבור כל תלמיד תוצג רשימת המקצועות בתוספת ציון המקצוע והערכת התלמיד ושם המורה המעדכן וזאת ע"מ לאפשר מעקב לאורך כל השנה על רמת התלמידים ואופן הערכת המורים, וכן יישום שיאפשר שליחת הודעה לכל מורה בבית הספר ע"מ לייעל את המעקב.
*	בתור מורה- אני מעוניין בממשק פשוט לתפעול שיאפשר בכל זמן נתון גישה לכל כיתה שבה אני מלמד ע"מ שאוכל לעדכן ציוני תלמידים ולתת הערכות ע"פ התקדמות התלמיד, ע"מ לאפשר בסוף השנה  הערכה כללית שתינתן על סמך נתוני השנה.
*	בתור מחנך- אני מעוניין בגישה לכל המידע של כל אחד מתלמידי (ציון/הערכה מכל מורה בתוספת שם המורה והמקצוע) וכן ביישום שיאפשר שליחת הודעה לכל מורה שמלמד בכיתתי, ע"מ שאוכל להזכיר/לבקש ממנו מתן הערכה / הסבר על הערכה -ציון במידת הצורך. 
*	בתור מזכירה- אני מעוניינת בממשק שיאפשר הנפקת תעודה באופן אוטומטי לאחר שכלול של כל הנתונים עבור כל תלמיד מכל אחד מצוות המורים המלמדים את התלמיד שיינתן כטבלה שמכילה את שם המקצוע וציונו, ע"מ לאפשר מעקב במידה והנפקת התעודה אינה מתאפשרת (מכל סיבה שהיא), אפשרות של שליחת הודעה לכל מחנך באופן אישי והעברת העניין לבירורו. וכן אפשרות עדכון תלמידים/כיתות/אנשי צוות במידת הצורך.

**Comment by robi-y** [comment]
Please complete the template for user story, or if you don't have it from the SRS just remove it
